<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);SA1501;CA1305;SA1633;SA1600;SA1200;SA1000;SA1309;SA1101;SA1502;SA1201;SA1202;SA1313;SA1503;SA1513;SA1516;SA1010;SA1127;SA1128;CA1000;CA1062;CA1307;CA1711;CA1716;CA2225;S4035</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

</Project>