<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ERP.Modules.Payroll</AssemblyName>
    <RootNamespace>ERP.Modules.Payroll</RootNamespace>
    <NoWarn>SA1000;CA1848;CA1031;CA1812;S2139;S6608;CS1591;SA1200;SA1600;SA1602;SA1309;SA1516;SA1413;SA1636;SA1202;SA1309;SA1010;CA1711;SA1127;CA1063;S3881;CA1051;SA1401;CA1716;SA1313;SA1633;SA1101;SA1502;SA1128;SA1503;S6602;S6964;CA1062;SA1116;CA1854;CA1024;CA1816;S6605;SA1116;CA2007;S6605;SA1010;CA1861;SA0001;SA1501;SA1515;SA1210;SA1201;SA1623;SA1117;CA1002;CA2227;SA1519;SA1513;SA1512;SA1407;CA1834;CA1305;CA1720;SA1204;SA1119;CA1822;S1144;S2325;SA1505;SA1508;S1186</NoWarn>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ERP.Core\ERP.Core.csproj" />
    <ProjectReference Include="..\..\ERP.Shared\ERP.Shared.csproj" />
    <ProjectReference Include="..\ERP.Modules.Platform\ERP.Modules.Platform.csproj" />
    <ProjectReference Include="..\ERP.Modules.GeneralLedger\ERP.Modules.GeneralLedger.csproj" />
    <ProjectReference Include="..\\ERP.Modules.ProjectAccounting\\ERP.Modules.ProjectAccounting.csproj" />
    <ProjectReference Include="..\\ERP.Modules.AccountsPayable\\ERP.Modules.AccountsPayable.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.8" />
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="FluentValidation" Version="11.10.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>
</Project>
