// Central navigation model for the ERP app shell.
// Single source of truth for the left main/sub menu, top header title, and breadcrumbs.
import {
  Home,
  Settings,
  BookOpen,
  Banknote,
  Receipt,
  Landmark,
  ShoppingCart,
  Boxes,
  Truck,
  Layers,
  FolderKanban,
  BadgeDollarSign,
  Wrench,
  BarChart3,
  Plug,
  ChevronRight,
  LayoutDashboard,
  TrendingUp,
  Building2,
  Users,
  UserCog,
  CreditCard,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  ScrollText,
  ShieldCheck,
  Shapes,
  Coins,
  Hash,
  Percent,
  Clock,
  PenLine,
  Sun,
  Scissors,
  Award,
  Package,
  Warehouse,
  ArrowLeftRight,
  RefreshCcw,
  ShieldAlert,
  Ship,
  ListChecks,
  GitPullRequest,
  FileText,
  Undo2,
  HardHat,
  FileSignature,
  Timer,
  MapPin,
  Calculator,
  Repeat,
  Inbox,
  Scale,
  Archive,
  Copy,
  Merge,
  Flag,
  BookText,
  PiggyBank,
  type LucideIcon,
} from 'lucide-react'

export interface NavSubItem {
  label: string
  to: string
}

export type NavColor =
  | 'sky' | 'slate' | 'indigo' | 'amber' | 'emerald' | 'teal' | 'orange'
  | 'violet' | 'cyan' | 'purple' | 'rose' | 'green' | 'blue' | 'fuchsia' | 'lime'

export interface NavModule {
  name: string
  /** Base route of the module (its index page). */
  href: string
  icon: LucideIcon
  /** Accent color family used for the sidebar icon chip and sub-menu icons. */
  color: NavColor
  /** Roles allowed to see this module. '*' = everyone. */
  roles: string[]
  sub: NavSubItem[]
}

/** Static Tailwind classes per accent color — kept literal so Tailwind can see them. */
export const NAV_CHIP_STYLES: Record<NavColor, string> = {
  sky: 'bg-sky-100 text-sky-600 dark:bg-sky-500/15 dark:text-sky-400',
  slate: 'bg-slate-200 text-slate-700 dark:bg-slate-500/20 dark:text-slate-300',
  indigo: 'bg-indigo-100 text-indigo-600 dark:bg-indigo-500/15 dark:text-indigo-400',
  amber: 'bg-amber-100 text-amber-600 dark:bg-amber-500/15 dark:text-amber-400',
  emerald: 'bg-emerald-100 text-emerald-600 dark:bg-emerald-500/15 dark:text-emerald-400',
  teal: 'bg-teal-100 text-teal-600 dark:bg-teal-500/15 dark:text-teal-400',
  orange: 'bg-orange-100 text-orange-600 dark:bg-orange-500/15 dark:text-orange-400',
  violet: 'bg-violet-100 text-violet-600 dark:bg-violet-500/15 dark:text-violet-400',
  cyan: 'bg-cyan-100 text-cyan-600 dark:bg-cyan-500/15 dark:text-cyan-400',
  purple: 'bg-purple-100 text-purple-600 dark:bg-purple-500/15 dark:text-purple-400',
  rose: 'bg-rose-100 text-rose-600 dark:bg-rose-500/15 dark:text-rose-400',
  green: 'bg-green-100 text-green-600 dark:bg-green-500/15 dark:text-green-400',
  blue: 'bg-blue-100 text-blue-600 dark:bg-blue-500/15 dark:text-blue-400',
  fuchsia: 'bg-fuchsia-100 text-fuchsia-600 dark:bg-fuchsia-500/15 dark:text-fuchsia-400',
  lime: 'bg-lime-100 text-lime-600 dark:bg-lime-500/15 dark:text-lime-400',
}

export const NAV_TEXT_STYLES: Record<NavColor, string> = {
  sky: 'text-sky-600 dark:text-sky-400',
  slate: 'text-slate-500 dark:text-slate-400',
  indigo: 'text-indigo-500 dark:text-indigo-400',
  amber: 'text-amber-500 dark:text-amber-400',
  emerald: 'text-emerald-500 dark:text-emerald-400',
  teal: 'text-teal-500 dark:text-teal-400',
  orange: 'text-orange-500 dark:text-orange-400',
  violet: 'text-violet-500 dark:text-violet-400',
  cyan: 'text-cyan-500 dark:text-cyan-400',
  purple: 'text-purple-500 dark:text-purple-400',
  rose: 'text-rose-500 dark:text-rose-400',
  green: 'text-green-500 dark:text-green-400',
  blue: 'text-blue-500 dark:text-blue-400',
  fuchsia: 'text-fuchsia-500 dark:text-fuchsia-400',
  lime: 'text-lime-600 dark:text-lime-400',
}

/** Keyword rules mapping a sub-menu label to a contextual icon (first match wins). */
const SUB_ICON_RULES: Array<[RegExp, LucideIcon]> = [
  [/report|aging|analysis/i, BarChart3],
  [/dashboard|inquiry|overview|summary|tie-out|stock by/i, LayoutDashboard],
  [/wip|forecast|trend|revaluat/i, TrendingUp],
  [/vendor w|vendor item|1099$|w-9/i, FileText],
  [/vendor/i, Building2],
  [/customer/i, Users],
  [/employee|technician/i, UserCog],
  [/payment term|manual check|payments?$/i, CreditCard],
  [/bank|lockbox|positive pay|nsf/i, Landmark],
  [/invoice|voucher|memo|billing|statement/i, Receipt],
  [/budget/i, PiggyBank],
  [/journal|ledger|posting|gr\/ir|accrual|consolidat/i, BookText],
  [/period|close|calendar|holiday/i, CalendarDays],
  [/approval|workflow|queue|delegation|match exception|three-way|four-way|receipt match|apply credit/i, ClipboardCheck],
  [/audit|history|notes/i, ScrollText],
  [/user|role|permission|segregation|sod|api key/i, ShieldCheck],
  [/segment/i, Shapes],
  [/currency|exchange/i, Coins],
  [/sequence|numbering/i, Hash],
  [/tax|withholding|dunning/i, Percent],
  [/timesheet/i, Clock],
  [/expense/i, PenLine],
  [/pto/i, Sun],
  [/deduction|garnish/i, Scissors],
  [/runs|payroll|pay code|union|certified/i, Award],
  [/setup|config/i, Settings],
  [/item|stock|kit|uom/i, Package],
  [/warehouse|bin|location|put-away/i, Warehouse],
  [/transfer|movement/i, ArrowLeftRight],
  [/count/i, ClipboardList],
  [/reorder|replenish|substitution|recurring/i, RefreshCcw],
  [/quarantine|scrap|expiration|negative|suspense/i, ShieldAlert],
  [/landed cost|freight|shipment|pick\/pack|ship/i, Ship],
  [/bom|work center|build order/i, Layers],
  [/project|task|subcontract/i, FolderKanban],
  [/change order/i, GitPullRequest],
  [/sales order|quote|blanket|order/i, ShoppingCart],
  [/return|rtv/i, Undo2],
  [/work order|dispatch/i, Wrench],
  [/equipment|asset|van/i, Boxes],
  [/contract|warranty/i, FileSignature],
  [/sla/i, Timer],
  [/territor/i, MapPin],
  [/estimate|pre-posting/i, Calculator],
  [/pm schedule|preventive/i, Repeat],
  [/reconcil/i, Scale],
  [/escheat|stale|archive/i, Archive],
  [/duplicate/i, Copy],
  [/deposit|cash receipt/i, Inbox],
  [/year-end/i, Flag],
  [/collection|allowance|credit limit|checklist/i, ListChecks],
]

/** Resolve a contextual icon for a sub-menu label; falls back to a chevron bullet. */
export function getSubIcon(label: string): LucideIcon {
  for (const [pattern, icon] of SUB_ICON_RULES) {
    if (pattern.test(label)) return icon
  }
  return ChevronRight
}

export const mainNavigation: NavModule[] = [
  {
    name: 'Dashboard',
    href: '/dashboard',
    icon: Home,
    color: 'sky',
    roles: ['*'],
    sub: [],
  },
  {
    name: 'Platform',
    href: '/platform',
    icon: Settings,
    color: 'slate',
    roles: ['Admin', 'SystemAdmin'],
    sub: [
      { label: 'Companies', to: '/platform/companies' },
      { label: 'Fiscal Periods', to: '/platform/fiscal-periods' },
      { label: 'Chart of Accounts', to: '/platform/accounts' },
      { label: 'Segment Types', to: '/platform/segment-types' },
      { label: 'Segment Values', to: '/platform/segment-values' },
      { label: 'Currencies', to: '/platform/currencies' },
      { label: 'Exchange Rates', to: '/platform/exchange-rates' },
      { label: 'Number Sequences', to: '/platform/number-sequences' },
      { label: 'Approval Workflows', to: '/platform/approval-workflows' },
      { label: 'Period Close', to: '/platform/period-close' },
      { label: 'API Keys', to: '/platform/api-keys' },
      { label: 'Approval Delegations', to: '/platform/approval-delegations' },
      { label: 'Holiday Calendar', to: '/platform/holiday-calendar' },
      { label: 'Segregation of Duties', to: '/platform/sod' },
      { label: 'Users', to: '/platform/users' },
      { label: 'Roles', to: '/platform/roles' },
      { label: 'Audit Log', to: '/platform/audit-logs' },
      { label: 'Reports', to: '/platform/reports' },
    ],
  },
  {
    name: 'General Ledger',
    href: '/gl',
    icon: BookOpen,
    color: 'indigo',
    roles: ['*'],
    sub: [
      { label: 'Journal Batches', to: '/gl/journal-batches' },
      { label: 'Recurring Templates', to: '/gl/recurring-templates' },
      { label: 'Allocation Rules', to: '/gl/allocation-rules' },
      { label: 'Budgets', to: '/gl/budgets' },
      { label: 'Budget Roll-Forward', to: '/gl/budget-rollforward' },
      { label: 'Revaluation', to: '/gl/revaluation' },
      { label: 'Reports', to: '/gl/reports' },
      { label: 'Consolidation', to: '/gl/consolidation' },
      { label: 'Account Inquiry', to: '/gl/account-inquiry' },
      { label: 'Pre-Posting Review', to: '/gl/pre-posting' },
      { label: 'Period-End Checklist', to: '/gl/period-end-checklist' },
      { label: 'Year-End Close', to: '/gl/year-end-close' },
      { label: 'Posting Suspense', to: '/gl/posting-suspense' },
    ],
  },
  {
    name: 'Accounts Payable',
    href: '/ap',
    icon: Banknote,
    color: 'amber',
    roles: ['*'],
    sub: [
      { label: 'Vendors', to: '/ap/vendors' },
      { label: 'Payment Terms', to: '/ap/payment-terms' },
      { label: 'Voucher Batches', to: '/ap/voucher-batches' },
      { label: 'Payments', to: '/ap/payments' },
      { label: 'Three-Way Match', to: '/ap/three-way-match' },
      { label: 'Match Exceptions', to: '/ap/match-exceptions' },
      { label: 'Backup Withholding', to: '/ap/backup-withholding' },
      { label: '1099', to: '/ap/1099' },
      { label: '1099 Processing', to: '/ap/1099-processing' },
      { label: 'Duplicate Invoice', to: '/ap/duplicate-invoice' },
      { label: 'Vendor W-9 / TIN', to: '/ap/vendor-w9' },
      { label: 'Bank Verify', to: '/ap/bank-verification' },
      { label: 'Cash Discount', to: '/ap/cash-discount' },
      { label: 'Escheatment', to: '/ap/escheatment' },
      { label: 'GR/IR Accrual', to: '/ap/grir-accrual' },
      { label: 'Vendor Statements', to: '/ap/vendor-statements' },
      { label: 'Reports', to: '/ap/reports' },
    ],
  },
  {
    name: 'Accounts Receivable',
    href: '/ar',
    icon: Receipt,
    color: 'emerald',
    roles: ['*'],
    sub: [
      { label: 'Customers', to: '/ar/customers' },
      { label: 'Invoice Batches', to: '/ar/invoice-batches' },
      { label: 'Cash Receipts', to: '/ar/cash-receipts' },
      { label: 'Credit / Debit Memos', to: '/ar/memos' },
      { label: 'Credit Limit', to: '/ar/credit-limit' },
      { label: 'Statements', to: '/ar/statements' },
      { label: 'Finance Charges', to: '/ar/finance-charges' },
      { label: 'Collections', to: '/ar/collections' },
      { label: 'Dunning', to: '/ar/dunning' },
      { label: 'Allowance (Doubtful)', to: '/ar/allowance' },
      { label: 'Resale Certificates', to: '/ar/resale-certificates' },
      { label: 'Apply Credit Memo', to: '/ar/credit-memo-apply' },
      { label: 'Aging by Basis', to: '/ar/aging-by-basis' },
      { label: 'Receipt Match', to: '/ar/cash-receipt-match' },
      { label: 'Reports', to: '/ar/reports' },
    ],
  },
  {
    name: 'Cash Management',
    href: '/cash',
    icon: Landmark,
    color: 'teal',
    roles: ['*'],
    sub: [
      { label: 'Bank Accounts', to: '/cash/bank-accounts' },
      { label: 'Deposits', to: '/cash/deposits' },
      { label: 'Bank Statements', to: '/cash/bank-statements' },
      { label: 'Reconciliations', to: '/cash/reconciliations' },
      { label: 'Transfers', to: '/cash/transfers' },
      { label: 'Bank Fees', to: '/cash/bank-fees' },
      { label: 'NSF', to: '/cash/nsf' },
      { label: 'Reports', to: '/cash/reports' },
      { label: 'GL Mapping', to: '/cash/gl-mapping' },
      { label: 'Lockbox', to: '/cash/lockbox' },
      { label: 'Stale Checks', to: '/cash/stale-checks' },
      { label: 'Positive Pay', to: '/cash/positive-pay' },
      { label: 'Fee Analysis', to: '/cash/fee-analysis' },
      { label: 'Forecast Horizon', to: '/cash/forecast-horizon' },
      { label: 'Outstanding Deposits', to: '/cash/outstanding-deposits' },
    ],
  },
  {
    name: 'Purchasing',
    href: '/purchasing',
    icon: ShoppingCart,
    color: 'orange',
    roles: ['*'],
    sub: [
      { label: 'Requisitions', to: '/purchasing/requisitions' },
      { label: 'Purchase Orders', to: '/purchasing/purchase-orders' },
      { label: 'Vendor Quotes', to: '/purchasing/vendor-quotes' },
      { label: 'Approval Queue', to: '/purchasing/approval-queue' },
      { label: 'Receipts', to: '/purchasing/receipts' },
      { label: 'PO Templates', to: '/purchasing/po-templates' },
      { label: 'Requisition Templates', to: '/purchasing/requisition-templates' },
      { label: 'Vendor Items', to: '/purchasing/vendor-items' },
      { label: 'Vendors', to: '/purchasing/vendors' },
      { label: 'Buyer Agents', to: '/purchasing/buyer-agents' },
      { label: 'Shipping Methods', to: '/purchasing/shipping-methods' },
      { label: 'FOB Terms', to: '/purchasing/fob-terms' },
      { label: 'Reports', to: '/purchasing/reports' },
    ],
  },
  {
    name: 'Inventory',
    href: '/inventory',
    icon: Boxes,
    color: 'violet',
    roles: ['*'],
    sub: [
      { label: 'Items', to: '/inventory/items' },
      { label: 'Categories', to: '/inventory/categories' },
      { label: 'Warehouses', to: '/inventory/warehouses' },
      { label: 'Bins', to: '/inventory/bins' },
      { label: 'Stock', to: '/inventory/stock' },
      { label: 'Transactions', to: '/inventory/transactions' },
      { label: 'Reservations', to: '/inventory/reservations' },
      { label: 'Quarantine', to: '/inventory/quarantine' },
      { label: 'Expiration', to: '/inventory/expiration' },
      { label: 'Revaluation', to: '/inventory/revaluation' },
      { label: 'Landed Cost', to: '/inventory/landed-cost' },
      { label: 'Landed Cost Allocations', to: '/inventory/landed-cost-allocations' },
      { label: 'Cycle Counts', to: '/inventory/cycle-counts' },
      { label: 'Physical Counts', to: '/inventory/physical-counts' },
      { label: 'Negative Overrides', to: '/inventory/negative-overrides' },
      { label: 'Movements', to: '/inventory/movements' },
      { label: 'Reorder', to: '/inventory/reorder' },
      { label: 'Substitutions', to: '/inventory/substitutions' },
      { label: 'Kits', to: '/inventory/kits' },
      { label: 'Consignment', to: '/inventory/consignment' },
      { label: 'Put-away / Picking', to: '/inventory/put-away-picking' },
      { label: 'Stock by Location', to: '/inventory/stock-by-location' },
      { label: 'Cycle Count Schedule', to: '/inventory/cycle-count-schedule' },
      { label: 'Scrap / Disposal', to: '/inventory/scrap' },
      { label: 'GL Tie-Out', to: '/inventory/gl-tie-out' },
      { label: 'Stock Card', to: '/inventory/stock-card' },
      { label: 'UOM Conversions', to: '/inventory/uom-conversions' },
      { label: 'UOM', to: '/inventory/uoms' },
      { label: 'Reports', to: '/inventory/reports' },
    ],
  },
  {
    name: 'Order Management',
    href: '/om',
    icon: Truck,
    color: 'cyan',
    roles: ['*'],
    sub: [
      { label: 'Sales Orders', to: '/om/sales-orders' },
      { label: 'Shipments', to: '/om/shipments' },
      { label: 'Returns', to: '/om/returns' },
      { label: 'Quotes', to: '/om/quotes' },
      { label: 'New Quote', to: '/om/quotes/new' },
      { label: 'Blanket Orders', to: '/om/blanket-orders' },
      { label: 'Substitution Offers', to: '/om/substitution-offers' },
      { label: 'Return-to-Vendor', to: '/om/rtv' },
      { label: 'Notes & History', to: '/om/order-notes' },
      { label: 'Order Dashboard', to: '/om/order-dashboard' },
      { label: 'Sales Analysis', to: '/om/sales-analysis' },
      { label: 'Commissions', to: '/om/commissions' },
      { label: 'ATP', to: '/om/atp' },
      { label: 'Freight', to: '/om/freight' },
      { label: 'Pick/Pack/Ship', to: '/om/pick-pack-ship' },
      { label: 'Reports', to: '/om/reports' },
      { label: 'Masters', to: '/om/masters' },
    ],
  },
  {
    name: 'Bill of Materials',
    href: '/bom',
    icon: Layers,
    color: 'purple',
    roles: ['*'],
    sub: [
      { label: 'BOMs', to: '/bom' },
      { label: 'Work Centers', to: '/bom/work-centers' },
      { label: 'Routing Operations', to: '/bom/routing-operations' },
      { label: 'Build Orders', to: '/bom/build-orders' },
      { label: 'Reports', to: '/bom/reports' },
    ],
  },
  {
    name: 'Project Accounting',
    href: '/projects',
    icon: FolderKanban,
    color: 'rose',
    roles: ['*'],
    sub: [
      { label: 'Projects', to: '/projects' },
      { label: 'Overview', to: '/projects/overview' },
      { label: 'Tasks', to: '/projects/tasks' },
      { label: 'Budgets', to: '/projects/budget' },
      { label: 'Costs', to: '/projects/costs' },
      { label: 'Billing', to: '/projects/billing' },
      { label: 'Change Orders', to: '/projects/change-orders' },
      { label: 'WIP / Analysis', to: '/projects/analysis' },
      { label: 'Reports', to: '/projects/reports' },
    ],
  },
  {
    name: 'Payroll',
    href: '/payroll',
    icon: BadgeDollarSign,
    color: 'green',
    roles: ['*'],
    sub: [
      { label: 'Employees', to: '/payroll/employees' },
      { label: 'Pay Codes', to: '/payroll/paycodes' },
      { label: 'Union / Certified', to: '/payroll/union' },
      { label: 'Timesheets', to: '/payroll/timesheets' },
      { label: 'Runs & Checks', to: '/payroll/runs' },
      { label: 'Expenses', to: '/payroll/expenses' },
      { label: 'Tax / W-4', to: '/payroll/tax' },
      { label: 'Deductions', to: '/payroll/deductions' },
      { label: 'PTO', to: '/payroll/pto' },
      { label: 'Manual Checks', to: '/payroll/manual' },
      { label: 'Reports', to: '/payroll/reports' },
      { label: 'Garnishments', to: '/payroll/garnishments' },
      { label: 'Setup & Config', to: '/payroll/setup' },
    ],
  },
  {
    name: 'Field Service',
    href: '/field-service',
    icon: Wrench,
    color: 'blue',
    roles: ['*'],
    sub: [
      { label: 'Work Orders', to: '/field-service/work-orders' },
      { label: 'Dispatch Board', to: '/field-service/dispatch' },
      { label: 'Technicians', to: '/field-service/technicians' },
      { label: 'Contracts', to: '/field-service/contracts' },
      { label: 'Equipment', to: '/field-service/equipment' },
      { label: 'SLAs', to: '/field-service/slas' },
      { label: 'Territories', to: '/field-service/territories' },
      { label: 'Rate Cards', to: '/field-service/rate-cards' },
      { label: 'Estimates', to: '/field-service/estimates' },
      { label: 'PM Schedules', to: '/field-service/pm' },
      { label: 'Van Stock', to: '/field-service/van-stock' },
      { label: 'Warranty', to: '/field-service/warranty' },
      { label: 'Reports', to: '/field-service/reports' },
    ],
  },
  {
    name: 'Reporting',
    href: '/reporting',
    icon: BarChart3,
    color: 'fuchsia',
    roles: ['*'],
    sub: [
      { label: 'Report Catalog', to: '/reporting/catalog' },
      { label: 'Executive Dashboard', to: '/reporting/executive' },
      { label: 'Report Viewer', to: '/reporting/viewer' },
      { label: 'Statement Designer', to: '/reporting/designer' },
      { label: 'Quick Query', to: '/reporting/quick-query' },
      { label: 'Drill-Back Viewer', to: '/reporting/drill-back' },
      { label: 'Report Scheduler', to: '/reporting/scheduler' },
      { label: 'Categories', to: '/reporting/categories' },
      { label: 'Parameter Sets', to: '/reporting/parameter-sets' },
      { label: 'Usage Analytics', to: '/reporting/usage' },
      { label: 'Sync Status', to: '/reporting/sync-status' },
    ],
  },
  {
    name: 'Integration',
    href: '/integration',
    icon: Plug,
    color: 'lime',
    roles: ['*'],
    sub: [],
  },
]

export interface NavResolved {
  module: NavModule
  sub?: NavSubItem
}
/** Resolve the current pathname to its module (and deepest matching sub-item). */
export function resolveNav(pathname: string): NavResolved | null {
  let moduleMatch: NavModule | null = null
  let subMatch: NavSubItem | undefined

  for (const m of mainNavigation) {
    if (pathname === m.href || pathname.startsWith(m.href + '/')) {
      moduleMatch = m
      let best: NavSubItem | undefined
      for (const s of m.sub) {
        if (pathname === s.to || pathname.startsWith(s.to + '/')) {
          if (!best || s.to.length > best.to.length) best = s
        }
      }
      subMatch = best
      break
    }
  }

  if (!moduleMatch) return null
  const result: NavResolved = { module: moduleMatch }
  if (subMatch) result.sub = subMatch
  return result
}
